"""add task execution tracking

Revision ID: 5e0195e535c5
Revises: f4c8b7d91a2e
Create Date: 2026-09-23 19:59:04.429302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0195e535c5'
down_revision: Union[str, Sequence[str], None] = 'f4c8b7d91a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('actual_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actual_duration_minutes')
    op.drop_column('tasks', 'actual_end')
    op.drop_column('tasks', 'actual_start')
    # ### end Alembic commands ###
