"""add routines

Revision ID: 801da09fd70b
Revises: c5d2a6655e06
Create Date: 2026-09-19 19:24:16.026220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801da09fd70b'
down_revision: Union[str, Sequence[str], None] = 'c5d2a6655e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routines_frequency', 'routines', ['frequency'], unique=False)
    op.create_index('ix_routines_goal_id', 'routines', ['goal_id'], unique=False)
    op.create_index('ix_routines_is_active', 'routines', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routines_is_active', table_name='routines')
    op.drop_index('ix_routines_goal_id', table_name='routines')
    op.drop_index('ix_routines_frequency', table_name='routines')
    op.drop_table('routines')
    # ### end Alembic commands ###
