"""add routine tracking to tasks

Revision ID: de7735abeee3
Revises: 801da09fd70b
Create Date: 2026-09-19 19:38:00.878293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7735abeee3'
down_revision: Union[str, Sequence[str], None] = '801da09fd70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('routine_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('routine_date', sa.Date(), nullable=True))
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_tasks_routine_date', 'tasks', ['routine_date'], unique=False)
    op.create_index('ix_tasks_routine_id', 'tasks', ['routine_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'routines', ['routine_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_routine_id', table_name='tasks')
    op.drop_index('ix_tasks_routine_date', table_name='tasks')
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'routine_date')
    op.drop_column('tasks', 'routine_id')
    # ### end Alembic commands ###
